hello:
	echo "Hello"

build:
	go build -o ./bin/client client.go

test:
	go test

run:
	./bin/client

run_createCM:
	./bin/client createCM

run_readCM:
	./bin/client readCM

run_readAllCM:
	./bin/client readAllCM

run_updateCM:
	./bin/client updateCM

run_deleteCM:
	./bin/client deleteCM